// <auto-generated />
namespace CreativeCollab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Create_PropertyTable_EstateAgents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_PropertyTable_EstateAgents));
        
        string IMigrationMetadata.Id
        {
            get { return "202307302244258_Create_PropertyTable_EstateAgents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
